name: test node project
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        types: [ opened ]
jobs:
    test: 
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./02-simple-nod-app
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 22.x
              uses: actions/setup-node@v3
              with:
                node-version: 22.x
            - run: npm ci
            - run: npm test
    build: 
        runs-on: ubuntu-latest
        needs: test
        defaults:
            run:
                working-directory: ./02-simple-nod-app
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 22.x
              uses: actions/setup-node@v3
              with:
                node-version: 22.x
            - name: Install dependencies and build
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Upload build artifacts
              uses: actions/upload-artifact@v7
              with:
                name: simple-node-app-artifacts
                path: |
                    ./dist
                    package.json
    deploy: 
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: ./02-simple-nod-app
        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v7
              with:
                name: simple-node-app-artifacts
            - name: list artifacts
              run: ls -la
            - name: deploy to server
              run: echo "Deploying to server..."
